src/Entity/Debt.php
<?php
declare(strict_types=1);

namespace App\Entity;

use App\Event\DebtAdded;
use App\Event\DebtRepaid;
use App\Event\EventTrait;
use App\Event\IDomainEvent;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="debts")
 */
class Debt implements IDomainEvent
{
    use EventTrait;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="float")
     */
    private $sum;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Currency", fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $currency;
    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;
    /**
     * @ORM\Column(type="string")
     */
    private $debtor;
    /**
     * @ORM\Column(type="boolean")
     */
    private $repaid = false;
    /**
     * @ORM\Column(type="date")
     */
    private $date;
    /**
     * @ORM\Column(type="date")
     */
    private $return_date;

    public function __construct(
        float $sum,
        Currency $currency,
        int $user_id,
        string $debtor,
        ?\DateTime $date = null
    ) {
        $this->sum = $sum;
        $this->currency = $currency;
        $this->user_id = $user_id;
        $this->debtor = $debtor;
        $this->date = $date ?? new \DateTime();

        $this->registerEvent(new DebtAdded($sum, $currency, $user_id));
    }

    public function repay($mark = false): void
    {
        if ($this->repaid === true) {
            return;
        }

        $this->repaid = true;
        $this->return_date = new \DateTime();

        if ($mark === false) {
            $this->registerEvent(new DebtRepaid($this->sum, $this->currency, $this->user_id));
        }
    }

    public function getId()
    {
        return $this->id;
    }

    public function getSum(): float
    {
        return $this->sum;
    }

    public function getCurrency(): Currency
    {
        return $this->currency;
    }

    public function getDebtor(): string
    {
        return $this->debtor;
    }

    public function isRepaid(): bool
    {
        return $this->repaid;
    }

    public function getDate(): \DateTime
    {
        return $this->date;
    }

    public function getReturnDate(): ?\DateTime
    {
        return $this->return_date;
    }
}

src/Controller/DebtController.php
<?php
declare(strict_types=1);

namespace App\Controller;

use App\DTO\DebtDTO;
use App\Entity\Debt;
use App\Repository\CurrencyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;

class DebtController extends AbstractController
{
    private $eventDispatcher;

    public function __construct(EventDispatcherInterface $eventDispatcher)
    {
        $this->eventDispatcher = $eventDispatcher;
    }

    public function list(): Response
    {
        $metaData = [
            'title' => 'debt list',
        ];
        $em = $this->getDoctrine()->getManager();
        $userId = $this->getUser()->getId();
        $data = $em->getRepository(Debt::class)->findBy(['user_id' => $userId]);

        return $this->render('debt/list.html.twig', [
            'debts' => $data,
            'metaData' => $metaData,
        ]);
    }

    public function new(CurrencyRepository $currencyRepository): Response
    {
        $currencies = $currencyRepository->getAll();

        return $this->render('debt/form.html.twig', [
            'currencies' => $currencies,
        ]);
    }

    public function create(DebtDTO $debtDTO, CurrencyRepository $currencyRepository): JsonResponse
    {
        $em = $this->getDoctrine()->getManager();
        $userId = $this->getUser()->getId();
        $currency = $currencyRepository->get((int) $debtDTO->currency);
        $date = $debtDTO->date ? \DateTime::createFromFormat('Y-m-d', $debtDTO->date) : null;

        $debt = new Debt(
            (float)$debtDTO->sum,
            $currency,
            $userId,
            $debtDTO->debtor,
            $date
        );

        foreach ($debt->popEvents() as $event) {
            $this->eventDispatcher->dispatch($event);
        }
        $em->persist($debt);
        $em->flush();

        return $this->json([
            'status' => 'ok',
        ]);
    }

    public function repay($id, $mark): JsonResponse
    {
        $em = $this->getDoctrine()->getManager();
        /** @var Debt $debt */
        $debt = $em->find(Debt::class, $id);

        if ($debt === null) {
            return $this->json(['status' => 'fail']);
        }

        $debt->repay($mark);
        foreach ($debt->popEvents() as $event) {
            $this->eventDispatcher->dispatch($event);
        }
        $em->flush();

        return $this->json(['status' => 'ok']);
    }
}

templates/debt/form.html.twig
<h4 class="mx-auto col-lg-6 col-md-12 text-center">Debt create</h4>
<form class="col-xl-12" action="{{ path('debt_create') }}" method="post" onsubmit="ajaxSend(event, this)">
    <div class="input-group mb-3 mx-auto col-lg-6 col-md-12">
        <input id="inputDebtSum" class="form-control" type="text" name="debt[sum]" autocomplete="off" placeholder="sum" inputmode="numeric">
        <div class="input-group-prepend">
            <label class="input-group-text currency-label" for="inputDebtSum"></label>
        </div>
        <div class="invalid-feedback"></div>
    </div>

    <div class="input-group mb-3 mx-auto col-lg-6 col-md-12">
        <input id="inputDebtDebtor" class="form-control" type="text" name="debt[debtor]" autocomplete="off" placeholder="debtor">
        <div class="input-group-prepend">
            <label class="input-group-text" for="inputDebtDebtor">#</label>
        </div>
        <div class="invalid-feedback"></div>
    </div>

    <div class="input-group mb-3 mx-auto col-lg-6 col-md-12">
        <select id="inputCurrency" class="custom-select currency-selector" name="debt[currency]" autocomplete="off" onchange="refreshCurrencyLabel()">
            {% for currency in currencies %}
                <option
                    value="{{ currency.id }}"
                    data-sign="{{ currency.sign }}"
                    {% if currency.name == app.request.get('c') %}
                        selected="selected"
                    {% endif %}
                >
                    {{ currency.name }}
                </option>
            {% endfor %}
        </select>
        <div class="input-group-prepend">
            <label class="input-group-text" for="inputCurrency">Currency</label>
        </div>
        <div class="invalid-feedback"></div>
    </div>

    <div class="input-group mb-3 mx-auto col-lg-6 col-md-12">
        <input id="inputDebtDate" class="form-control datepicker" type="text" name="debt[date]" autocomplete="off" placeholder="{{ "now"|date("Y-m-d") }}">
        <div class="input-group-prepend">
            <label class="input-group-text" for="inputDebtDate">Date</label>
        </div>
        <div class="invalid-feedback"></div>
    </div>

    <input type="hidden" name="_csrf_token" value="{{ csrf_token('debt_form') }}">

    <div class="input-group col-lg-6 col-md-12 mb-3 mx-auto">
        <button type="submit" class="btn btn-primary btn-block">send</button>
    </div>
</form>

templates/debt/list.html.twig
{% extends 'template/sbadmin.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row" id="form-wrapper"></div>
        {% if debts is empty %}
            <p>No data!</p>
        {% else %}
            <table class="table table-bordered" width="100%" cellspacing="0">
                <tr>
                    <th>Sum</th>
                    <th>Debtor</th>
                    <th>Date</th>
                    <th>Repay with cash</th>
                    <th>Mark as repaid</th>
                </tr>
                {% for debtData in debts %}
                    <tr>
                        <td>{{ debtData.sum | c_number_format }} {{ debtData.currency.sign }}</td>
                        <td>{{ debtData.debtor }}</td>
                        <td>{{ debtData.date | date("Y-m-d") }}</td>

                        {% if debtData.repaid %}
                            <td colspan="2">Repaid - {{ debtData.returnDate | date("Y-m-d") }}</td>

                        {% else %}
                            <td><i data-id="{{ debtData.id }}" class="reply-button reply-button-style fas fa-fw fa-reply"></i></td>
                            <td><i data-id="{{ debtData.id }}" class="check-button reply-button-style fas fa-fw fa-check"></i></td>
                        {% endif %}

                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% endif %}
    </div>
{% endblock %}

{% block css_page %}
    <link rel="stylesheet" href="{{ asset('vendor/bootstrap/css/bootstrap-datepicker3.standalone.min.css') }}">
    <style>
        .reply-button-style {
            font-size: 1.3rem;
            cursor: pointer;
        }

        .reply-button-style:hover {
            color: red;
        }
    </style>
{% endblock %}

{% block js_page %}
    <script src="{{ asset('vendor/bootstrap/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        $('.reply-button').on('click', function () {
            if (confirm('Are you sure?')) {
                var id = $(this).data('id')
                deleteAction(id, false);
            }
        });

        $('.check-button').on('click', function () {
            if (confirm('Are you sure?')) {
                var id = $(this).data('id')
                deleteAction(id, true);
            }
        });

        var deleteAction = function (id, mark) {
            var url = '/debt/repay/' + id;

            if (mark === true) {
                url += '/mark'
            }

            $.ajax({
                type: 'GET',
                url: url,
            })
                .done(function (data) {
                    console.log(data);
                })
                .fail(function () {
                    alert('fail');
                });
        }

        var fromCall = function (url) {
            $.ajax({
                type: 'GET',
                url: url,
                dataType: 'html',
                data: {}
            })
                .done(function (data, textStatus, jqXHR) {
                    if (jqXHR.status === 200) {
                        insertForm(data);
                        refreshCurrencyLabel();
                        $('.datepicker').datepicker({
                            autoclose: true,
                            clearBtn: true,
                            disableTouchKeyboard: true,
                            startDate: '-1y',
                            endDate: '+1y',
                            format: 'yyyy-mm-dd',
                            todayHighlight: true,
                            weekStart: 1,
                        });
                    }
                });
        };

        var insertForm = function (html) {
            $('#form-wrapper').html(html);
        };

        var ajaxSend = function(e, o) {
            e.preventDefault();
            $('input, select').removeClass('is-invalid');

            var xhrOptions = {
                type: $(o).attr('method'),
                url: $(o).attr('action'),
                data: $(o).serialize()
            };

            $.ajax(xhrOptions)
                .done(function (data) {
                    switch (data.status) {
                        // TODO: hard code
                        case 'ok':
                            onAjaxSuccess();
                            break;

                        case 'validation error':
                            onValidationError(data.errors);
                            break;

                        case 'no entity found':
                            onNoEntityFound(data.errors);
                            break;
                    }
                })
                .fail(function () {
                    alert('fail');
                });
        };

        var onAjaxSuccess = function() {
            $('#form-wrapper').append('<p>Request Success</p>');
        };

        var onValidationError = function(errors) {
            $(errors).each(function(k, v) {
                $('[name="'+v.path+'"]').addClass('is-invalid');
                $('[name="'+v.path+'"]~.invalid-feedback').html(v.message);
            })
        };

        var onNoEntityFound = function(errors) {
            alert('entity ' + errors.entity + ' with id ' + errors.id + ' not found');
        };

        var refreshCurrencyLabel = function () {
            var currencySelector = $('.currency-selector')[0];
            if (currencySelector) {
                $('.currency-label').html($($('.currency-selector')[0].selectedOptions[0]).attr('data-sign'));
            }
        };

        fromCall('/debt/new');
    </script>
{% endblock %}